### ISSUE TITLE
Downsampling script may fail with `IndexError`

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/ncov2019-artic-nf#48]
Under some circumstances, the `downsample_amplicons.py` script may fail with an `IndexError`:

```
Traceback (most recent call last):
  File "downsample_amplicons.py", line 308, in <module>
    main(args)
  File "downsample_amplicons.py", line 280, in main
    genome_checkpoint_depths = [depths[checkpoint] for checkpoint in genome_checkpoints]
  File "downsample_amplicons.py", line 280, in <listcomp>
    genome_checkpoint_depths = [depths[checkpoint] for checkpoint in genome_checkpoints]
IndexError: list index out of range
```

The exact circumstances are currently unclear.

**Comment by dfornika** [comment]
This error occurs when we attempt to analyze a virus with a genome size greater than 30 kb. We pre-allocate an array of sequence depths for each position in the genome here:

https://github.com/BCCDC-PHL/ncov2019-artic-nf/blob/f1e41605a7a5dd14d9434f7516eb0a6eed83aee5/bin/downsample_amplicons.py#L232

...but we make the assumption that the genome size is no greater than 30 kb. So then later, when we attempt to look up the depth at some 'checkpoint' position that is greater than 30000, this results in attempting to access a value from the `depths` array that is beyond the maximum index.

https://github.com/BCCDC-PHL/ncov2019-artic-nf/blob/f1e41605a7a5dd14d9434f7516eb0a6eed83aee5/bin/downsample_amplicons.py#L264
